---
version: "3.9"

services:
  
  ljordan:
      image: "10.0.0.10:5000/dr.hpotter/ljordan"
    build:
      context: ljordan
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /ljordan/hpotter_api:/hpotter.db
  hpotter:
      image: "10.0.0.10:5000/dr.hpotter/hpotter"
    build:
      context: hpotter
      dockerfile: Dockerfile
    volumes:
      - /hpotter:/hpotter.db
  view:
      image: "10.0.0.10:5000/dr.hpotter/viewserve"
    build:
      context: viewserve
      dockerfile: Dockerfile
    ports:
      - "8080:80"
volumes:
  hpotter.db:
            
 

