
version: "3.9"

services:

  sshd:
    image: "privsim/multiarch-dr.hpotter:sshd"
    build: 
      context: sshd
      dockerfile: Dockerfile

  telnetd:
    image: "privsim/multiarch-dr.hpotter:telnetd"
    build:
      context: telnetd
      dockerfile: Dockerfile

  bindd:
    image: "privsim/multiarch-dr.hpotter:bindd"
    build:
      context: bindd
      dockerfile: Dockerfile

  ljordan:
    image: "privsim/multiarch-dr.hpotter:ljordan"
    build:
      context: ljordan
      dockerfile: Dockerfile
    volumes:
      - /ljordan/hpotter_api:/hpotter.db

  hpotter:
    image: "privsim/multiarch-dr.hpotter:hpotter"
    build:
      context: hpotter
      dockerfile: Dockerfile
    volumes:
      - /hpotter:/hpotter.db

  view:
    image: "privsim/multiarch-dr.hpotter:viewserve"
    build:
      context: viewserve
      dockerfile: Dockerfile
    ports:
      - "8080:80"
volumes:
  hpotter.db:
            
 

